export type Event = {
  link: string;
  startDate: string;
  endDate: string;
  title: string;
  description: string;
  image: string;
  time: string;
  location: string;
  zip: string;
  city: string;
  district: string;
  area: string;
  street: string;
  streetNumber: string;
  transportation: string;
  latitude: number;
  longitude: number;
  fee: string;
};
